# Generated by Django 3.2.13 on 2022-07-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0005_classname_pr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classname',
            name='image',
        ),
    ]
