# Generated by Django 3.2.13 on 2022-07-29 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0007_alter_classname_pr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='pr',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
