# Generated by Django 3.2.13 on 2022-08-01 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0010_alter_classname_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='cname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='presence.classname'),
        ),
    ]
