# Generated by Django 3.2.13 on 2022-08-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0011_userdata_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.classname'),
        ),
    ]
