# Generated by Django 3.2.13 on 2022-08-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0012_alter_userdata_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='cname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', related_query_name='user_data', to='presence.classname'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='nim',
            field=models.CharField(max_length=255),
        ),
    ]
