# Generated by Django 3.2.13 on 2022-08-03 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0013_auto_20220802_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='cname',
        ),
        migrations.AddField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(related_name='stud', related_query_name='stud', to=settings.AUTH_USER_MODEL),
        ),
    ]
