# Generated by Django 3.2.13 on 2022-08-05 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0014_auto_20220803_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='stud', related_query_name='stud', to=settings.AUTH_USER_MODEL),
        ),
    ]
