# Generated by Django 3.2.13 on 2022-08-13 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0015_alter_classname_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateqrcode',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_class', related_query_name='from_class', to='presence.classname'),
        ),
        migrations.AlterField(
            model_name='recap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recap', related_query_name='user_recap', to=settings.AUTH_USER_MODEL),
        ),
    ]
