# Generated by Django 3.2.13 on 2022-08-17 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0016_auto_20220814_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='generateqrcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
