# Generated by Django 3.2.13 on 2022-08-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0017_generateqrcode_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='classname',
            name='lecture_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
