# Generated by Django 3.2.13 on 2022-09-21 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presence', '0018_classname_lecture_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recap',
            name='presence',
            field=models.CharField(default='Hadir', max_length=255),
        ),
        migrations.AlterField(
            model_name='classname',
            name='lecture_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nama Dosen : '),
        ),
        migrations.AlterField(
            model_name='classname',
            name='pr',
            field=models.ManyToManyField(blank=True, related_name='assist', related_query_name='assist', to=settings.AUTH_USER_MODEL),
        ),
    ]
