# Generated by Django 3.2.13 on 2022-07-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
