# Generated by Django 3.2.15 on 2022-09-27 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0002_delete_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenToResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(blank=True, null=True, related_name='user_pass', related_query_name='user_pass', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
