# Generated by Django 3.2.15 on 2022-10-12 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0019_auto_20220921_1508'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0005_studentscore_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='class_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_score', related_query_name='user_score', to='presence.classname'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', related_query_name='score', to=settings.AUTH_USER_MODEL),
        ),
    ]
